version: "3.8"
volumes: 
  database: ~

services:
  php-apache: 
    build: .
    container_name: php-apache
    ports: 
      - "8080:80"
    depends_on:
      - mariadb

  mariadb:
    image: oussamasaidi1/my-php_apache-app:latest
    restart: always
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: azureuserdatabase
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes: 
      - database:/var/lib/mysql
